---
- name: Setup Server Backend Wildan
  hosts: my_servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install utilities
      apt:
        name:
          - git
          - curl
        state: present

    - name: Create project directory
      file:
        path: /home/wildan-fq/app-backend
        state: directory
        owner: wildan-fq
        group: wildan-fq
        mode: "0755"
