name: Deploy API to GCP

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./notes/server/sqllite
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            podman pull ghcr.io/${{ github.repository }}:latest
            podman stop go-api || true
            podman rm go-api || true
            podman run -d \
              --name go-api \
              -p 8080:8080 \
              -v /home/pronus_programmernusantara/sqlite-data:/root/data:Z \
              ghcr.io/${{ github.repository }}:latest
